import {
  BarChart3,
  Boxes,
  Cable,
  LayoutDashboard,
  Layers3,
  ReceiptText,
  Server,
  Settings2,
  Tags,
  Users,
  Wallet,
} from "lucide-react";

export const navigation = [
  {
    href: "/",
    label: "概览",
    group: "工作台",
    icon: LayoutDashboard,
    keywords: "dashboard 总览",
    description: "账户与模型概况",
  },
  {
    href: "/usage/",
    label: "用量记录",
    group: "工作台",
    icon: BarChart3,
    keywords: "usage 费用 tokens 消费",
    description: "实际请求与费用记录",
  },
  {
    href: "/users/",
    label: "用户管理",
    group: "用户与订阅",
    icon: Users,
    keywords: "user 用户 钱包",
    description: "用户资料与钱包记录",
  },
  {
    href: "/consumers/",
    label: "虚拟账户",
    group: "用户与订阅",
    icon: Users,
    keywords: "consumer 订阅 登录 身份",
    description: "消费身份、订阅与执行路由",
  },
  {
    href: "/subscriptions/",
    label: "订阅管理",
    group: "用户与订阅",
    icon: Layers3,
    keywords: "subscription 用户订阅 续期",
    description: "用户的平台订阅与权益",
  },
  {
    href: "/plans/",
    label: "套餐管理",
    group: "交易管理",
    icon: Layers3,
    keywords: "plan 权益 限额",
    description: "模型权限与订阅权益",
  },
  {
    href: "/orders/",
    label: "订单管理",
    group: "交易管理",
    icon: ReceiptText,
    keywords: "order 购买 续订 升级 收费",
    description: "订单、报价与钱包支付记录",
  },
  {
    href: "/wallet-entries/",
    label: "流水管理",
    group: "交易管理",
    icon: Wallet,
    keywords: "wallet ledger 流水 余额 收支",
    description: "用户余额变动记录",
  },
  {
    href: "/coupons/",
    label: "优惠券管理",
    group: "交易管理",
    icon: Tags,
    keywords: "coupon 优惠码 折扣",
    description: "优惠金额、适用套餐与使用次数",
  },
  {
    href: "/suppliers/",
    label: "供应账户",
    group: "供应资源",
    icon: Server,
    keywords: "supplier 上游 授权",
    description: "上游授权与执行账户",
  },
  {
    href: "/supplier-tags/",
    label: "标签管理",
    group: "供应资源",
    icon: Tags,
    keywords: "tag 标签 号池 平台",
    description: "供应标签与号池管理",
  },
  {
    href: "/proxies/",
    label: "出站代理",
    group: "供应资源",
    icon: Cable,
    keywords: "proxy 网络 连接",
    description: "供应账户的网络连接",
  },
  {
    href: "/models/",
    label: "计费配置",
    group: "系统配置",
    icon: Boxes,
    keywords: "model 价格 计费",
    description: "模型目录与计费价格",
  },
  {
    href: "/settings/",
    label: "系统设置",
    group: "系统配置",
    icon: Settings2,
    keywords: "settings 管理员 安全",
    description: "服务策略与管理员设置",
  },
] as const;

export const navigationGroups = [...new Set(navigation.map((item) => item.group))];

export function isCurrentPage(pathname: string, href: string) {
  return href === "/" ? pathname === "/" : pathname.startsWith(href.slice(0, -1));
}
