import type { BusinessField } from "./api";

export const accountConfigGroups = [
  { key: "account", label: "账户与订阅", sections: [] },
  {
    key: "features",
    label: "功能开关",
    sections: [
      "desktop_model_policy",
      "computer_use_policy",
      "account_settings",
      "user_settings",
      "feature_bootstrap",
      "trusted_contact",
      "sites",
      "first_party",
      "referrals",
      "gift_credits",
    ],
  },
  { key: "profile", label: "个人资料", sections: ["profile", "age"] },
  { key: "conversation", label: "会话与附件", sections: ["conversation_metadata"] },
  {
    key: "messages",
    label: "提示与公告",
    sections: ["system_hints", "beacons", "workspace_messages"],
  },
  { key: "offers", label: "优惠与定价", sections: ["pricing", "discount_offer"] },
];

// Frontend-owned field definitions. API responses supply values and revisions only.
export const accountSections: {
  key: string;
  label: string;
  description: string;
  readonly: boolean;
  fields: BusinessField[];
}[] = [
  {
    key: "desktop_model_policy",
    label: "Desktop 推理强度设置",
    description: "控制推理强度入口及 Ultra 档位的可用性，用户选择由 Desktop 保存。",
    readonly: false,
    fields: [
      {
        path: ["reasoning_settings_enabled"],
        label: "显示推理强度设置",
        group: "模型设置入口",
        kind: "boolean",
        description: "在 Desktop 配置页显示“可用推理强度”；具体级别取决于模型实际能力。",
        choices: [],
        optional: false,
      },
      {
        path: ["ultra_effort_available"],
        label: "显示模型支持的 Ultra 档位",
        group: "模型设置入口",
        kind: "boolean",
        description: "允许客户端展示已有模型的 Ultra 能力；不替用户选中该档位或改变审批权限。",
        choices: [],
        optional: false,
      },
    ],
  },
  {
    key: "computer_use_policy",
    label: "浏览器与电脑操控",
    description: "管理浏览器与电脑操控的可用性，本机权限仍由客户端授权。",
    readonly: false,
    fields: [
      {
        path: ["browser_enabled"],
        label: "允许浏览器操控",
        group: "服务可用性",
        kind: "boolean",
        description: "允许客户端使用 Chrome 等浏览器的原生扩展；不会代装扩展或修改审批。",
        choices: [],
        optional: false,
      },
      {
        path: ["computer_enabled"],
        label: "允许电脑操控",
        group: "服务可用性",
        kind: "boolean",
        description: "允许 Desktop 显示本机电脑操控能力；仍需客户端插件、系统权限和本机审批。",
        choices: [],
        optional: false,
      },
    ],
  },
  {
    key: "cloud_preferences",
    label: "云端偏好",
    description: "客户端维护的分支命名和差异显示偏好。",
    readonly: true,
    fields: [],
  },
  {
    key: "feature_bootstrap",
    label: "客户端功能",
    description: "管理个性风格、自定义指令和演示文稿功能的入口。",
    readonly: false,
    fields: [
      {
        path: ["feature_gates", "3522875721", "value"],
        label: "个性风格",
        group: "客户端功能",
        kind: "boolean",
        description: "在客户端提供个性风格选项。",
        choices: [],
        optional: true,
      },
      {
        path: ["feature_gates", "3819087019", "value"],
        label: "自定义指令",
        group: "客户端功能",
        kind: "boolean",
        description: "允许用户设置自己的执行指令。",
        choices: [],
        optional: true,
      },
      {
        path: ["feature_gates", "1966011307", "value"],
        label: "演示文稿大纲",
        group: "客户端功能",
        kind: "boolean",
        description: "客户端的演示文稿大纲功能开关。",
        choices: [],
        optional: true,
      },
      {
        path: ["feature_gates", "1215078560", "value"],
        label: "演示文稿大纲入口",
        group: "客户端功能",
        kind: "boolean",
        description: "控制客户端演示文稿大纲入口的展示。",
        choices: [],
        optional: true,
      },
    ],
  },
  {
    key: "profile",
    label: "个人资料",
    description: "头像及个人简介；身份名称和邮箱在账号表单维护。",
    readonly: false,
    fields: [],
  },
  {
    key: "desktop_preferences",
    label: "旧版协议配置",
    description: "兼容能力由已实现的协议自动提供，此历史记录不再控制客户端语言和个人页。",
    readonly: true,
    fields: [],
  },
  {
    key: "profile_page",
    label: "个人信息页",
    description: "客户端显示名称和用户名留空时使用账号资料；统计来自本账号实际记录。",
    readonly: true,
    fields: [],
  },
  {
    key: "account_settings",
    label: "工作区策略",
    description: "管理工作模式、第三方 GPT、测试版和额度申请入口。",
    readonly: false,
    fields: [
      {
        path: ["member_profiles_enabled"],
        label: "显示成员个人资料",
        group: "工作区策略",
        kind: "boolean",
        description: "控制当前工作区的个人资料入口。",
        choices: [],
        optional: true,
      },
      {
        path: ["admin_work_mode_enabled"],
        label: "允许工作模式",
        group: "工作区策略",
        kind: "boolean",
        description: "客户端工作模式策略。",
        choices: [],
        optional: true,
      },
      {
        path: ["admin_work_local_enabled"],
        label: "允许本地工作",
        group: "工作区策略",
        kind: "boolean",
        description: "客户端本地执行策略；保留本地权限检查。",
        choices: [],
        optional: true,
      },
      {
        path: ["beta_settings", "enable_message_feedback"],
        label: "允许消息反馈",
        group: "工作区策略",
        kind: "boolean",
        description: "控制客户端的消息反馈入口。",
        choices: [],
        optional: true,
      },
      {
        path: ["desktop_app_beta_policy"],
        label: "桌面测试版策略",
        group: "工作区策略",
        kind: "select",
        description: "客户端支持的四种测试版选择策略。",
        choices: [
          ["blocked", "禁止"],
          ["optional_default_off", "允许，默认关闭"],
          ["optional_default_on", "允许，默认开启"],
          ["required", "必须启用"],
        ],
        optional: true,
      },
      {
        path: ["allow_third_party_gpts"],
        label: "第三方 GPT 策略",
        group: "工作区策略",
        kind: "select",
        description: "控制客户端第三方 GPT 使用策略。",
        choices: [
          ["allow_all", "全部允许"],
          ["allow_none", "全部禁止"],
          ["allow_specific", "仅指定范围"],
        ],
        optional: true,
      },
      {
        path: ["usage_limit_increase_request", "kind"],
        label: "额度申请入口",
        group: "额度申请",
        kind: "select",
        description: "选择是否向用户提供本系统的申请入口。",
        choices: [
          ["disabled", "不显示"],
          ["custom", "自定义申请入口"],
          ["openai_native", "客户端原生入口"],
        ],
        optional: false,
      },
      {
        path: ["usage_limit_increase_request", "instructions"],
        label: "申请说明",
        group: "额度申请",
        kind: "text",
        description: "自定义入口中显示的说明。",
        choices: [],
        optional: true,
      },
      {
        path: ["usage_limit_increase_request", "request_url"],
        label: "申请链接",
        group: "额度申请",
        kind: "url",
        description: "自定义入口的 HTTP(S) 地址。",
        choices: [],
        optional: true,
      },
    ],
  },
  {
    key: "user_settings",
    label: "文件库与推荐",
    description: "管理文件库和推荐功能的可用性；用户偏好在记录查询中查看。",
    readonly: false,
    fields: [
      {
        path: ["flags", "bazaar_consent_required"],
        label: "推荐功能需要同意",
        group: "界面可用状态",
        kind: "boolean",
        description: "要求客户端显示推荐功能同意流程。",
        choices: [],
        optional: true,
      },
      {
        path: ["flags", "bazaar_personalization_unavailable"],
        label: "推荐个性化不可用",
        group: "界面可用状态",
        kind: "boolean",
        description: "控制客户端个性化功能的可用状态。",
        choices: [],
        optional: true,
      },
      {
        path: ["flags", "file_library_enabled_for_registration_country"],
        label: "所在地区可使用文件库",
        group: "界面可用状态",
        kind: "boolean",
        description: "本地配置的界面可用状态，不代表官方地区资格。",
        choices: [],
        optional: true,
      },
    ],
  },
  {
    key: "config_bundle",
    label: "客户端配置包",
    description: "官方客户端解析的 TOML 配置与要求。",
    readonly: true,
    fields: [],
  },
  {
    key: "referrals",
    label: "邀请资格",
    description: "本虚拟账号的邀请展示配置。",
    readonly: false,
    fields: [],
  },
  {
    key: "referral_tracking",
    label: "邀请记录",
    description: "维护此虚拟账号的邀请展示记录；保存记录不会发送邮件。",
    readonly: true,
    fields: [],
  },
  {
    key: "payment_methods",
    label: "支付资料",
    description: "自行维护的虚拟支付资料，不执行真实扣款。",
    readonly: true,
    fields: [],
  },
  {
    key: "trusted_contact",
    label: "信任联系人",
    description: "联系人功能及本地联系人资料。",
    readonly: false,
    fields: [
      {
        path: ["enabled"],
        label: "提供信任联系人功能",
        group: "功能可用性",
        kind: "boolean",
        description: "控制功能入口；联系人资料由客户端维护。",
        choices: [],
        optional: false,
      },
    ],
  },
  {
    key: "family",
    label: "家庭资料",
    description: "本地虚拟家庭关系；null 表示尚未配置。",
    readonly: true,
    fields: [],
  },
  {
    key: "pricing",
    label: "地区定价配置",
    description: "以地区代码为键的本系统定价配置，不代表官方报价。",
    readonly: false,
    fields: [],
  },
  {
    key: "gift_credits",
    label: "赠送资格",
    description: "本虚拟账号的赠送功能展示配置。",
    readonly: false,
    fields: [],
  },
  {
    key: "notification_settings",
    label: "通知设置",
    description: "按 category、options/channel 配置通知渠道。",
    readonly: true,
    fields: [],
  },
  {
    key: "notifications",
    label: "通知记录",
    description: "本虚拟账号的通知；修改后向其事件连接发布更新。",
    readonly: true,
    fields: [],
  },
  {
    key: "pins",
    label: "账号置顶记录",
    description: "本账号置顶项目及会话，使用客户端的 item_type 和资源 ID。",
    readonly: true,
    fields: [],
  },
  {
    key: "first_party",
    label: "侧栏功能资格",
    description: "本虚拟账号的 finances 与 health_eligibility 配置。",
    readonly: false,
    fields: [],
  },
  {
    key: "projects",
    label: "账号云项目记录",
    description: "本账号项目记录，items 每项包含 gizmo 和 conversations。",
    readonly: true,
    fields: [],
  },
  {
    key: "system_hints",
    label: "系统提示",
    description: "客户端可选提示列表。",
    readonly: false,
    fields: [],
  },
  {
    key: "age",
    label: "年龄资料",
    description: "自行配置的年龄信息，不等同于官方年龄认证。",
    readonly: false,
    fields: [],
  },
  {
    key: "models",
    label: "ChatGPT 模型目录",
    description: "ChatGPT 页面模型目录；与 Codex 模型目录协议不同。",
    readonly: true,
    fields: [],
  },
  {
    key: "conversation_metadata",
    label: "会话与附件",
    description: "配置默认模型和附件上传限制。",
    readonly: false,
    fields: [
      {
        path: ["default_model_slug"],
        label: "默认模型",
        group: "服务端默认值",
        kind: "string",
        description: "客户端未指定模型时使用。",
        choices: [],
        optional: true,
      },
      {
        path: ["file_attachment_limits", "max_size_mb"],
        label: "单个文件大小上限（MB）",
        group: "上传限制",
        kind: "integer",
        description: "设置附件限制时需填写此项。",
        choices: [],
        optional: true,
      },
      {
        path: ["file_attachment_limits", "max_count_per_turn"],
        label: "每轮文件数上限",
        group: "上传限制",
        kind: "integer",
        description: "留空使用客户端默认。用量进度由实际记录生成。",
        choices: [],
        optional: true,
      },
    ],
  },
  {
    key: "auto_top_up",
    label: "自动充值展示",
    description: "本系统的展示配置，不执行供应账户的充值操作。",
    readonly: true,
    fields: [],
  },
  {
    key: "discount_offer",
    label: "优惠展示",
    description: "本系统优惠资料。",
    readonly: false,
    fields: [],
  },
  {
    key: "sites",
    label: "站点资格",
    description: "本虚拟账号的站点配置。",
    readonly: false,
    fields: [],
  },
  {
    key: "verified_access",
    label: "访问资格",
    description: "本虚拟账号的授权配置。",
    readonly: true,
    fields: [],
  },
  {
    key: "automations",
    label: "自动化配置",
    description: "本账号自动化定义；执行状态不能冒充已执行结果。",
    readonly: true,
    fields: [],
  },
  {
    key: "beacons",
    label: "首页公告",
    description: "本虚拟账号的公告。",
    readonly: false,
    fields: [],
  },
  {
    key: "workspace_messages",
    label: "工作区消息",
    description: "本虚拟账号的工作区消息列表。",
    readonly: false,
    fields: [],
  },
  {
    key: "installed_plugins",
    label: "已安装插件",
    description: "本虚拟账号自身的安装记录。",
    readonly: true,
    fields: [],
  },
  {
    key: "voice",
    label: "语音选择",
    description: "客户端选择的语音名称。",
    readonly: true,
    fields: [],
  },
  {
    key: "onboarding",
    label: "引导状态",
    description: "客户端完成引导后保存；网页亦可维护。",
    readonly: true,
    fields: [],
  },
  {
    key: "browser_settings",
    label: "浏览器设置",
    description: "偏好与站点规则；保存使用版本校验，避免覆盖客户端并发修改。",
    readonly: true,
    fields: [],
  },
];

export const clientRecordFields: Record<string, BusinessField[]> = {
  cloud_preferences: [],
  desktop_preferences: [],
  profile_page: [],
  user_settings: [
    {
      path: ["settings", "connector_search_enabled"],
      label: "在搜索中使用连接器",
      group: "搜索与文件",
      kind: "boolean",
      description: "客户端默认开启；连接器仍需实际连接和授权。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "file_library_auto_reference"],
      label: "自动引用文件库",
      group: "搜索与文件",
      kind: "boolean",
      description: "允许客户端自动引用本账号文件库中的资料。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "memory_in_search"],
      label: "搜索时使用记忆",
      group: "搜索与文件",
      kind: "boolean",
      description: "控制客户端搜索记忆偏好。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "instant_answers_enabled"],
      label: "即时回答",
      group: "回答与编辑器",
      kind: "boolean",
      description: "客户端默认开启。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "task_suggestions_enabled"],
      label: "任务建议",
      group: "回答与编辑器",
      kind: "boolean",
      description: "客户端默认开启任务建议。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "default_to_study_mode"],
      label: "默认使用学习模式",
      group: "回答与编辑器",
      kind: "boolean",
      description: "控制新聊天的学习模式偏好。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "show_expanded_code_view"],
      label: "展开代码视图",
      group: "回答与编辑器",
      kind: "boolean",
      description: "在客户端显示展开的代码内容。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "model_picker_prefers_auto_for_instant_preset"],
      label: "即时预设优先自动选择模型",
      group: "回答与编辑器",
      kind: "boolean",
      description: "保留客户端对即时预设的模型选择偏好。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "model_picker_persists_ultra_effort"],
      label: "模型选择器滑块中的 Ultra",
      group: "回答与编辑器",
      kind: "boolean",
      description: "客户端选择是否将 Ultra 显示为模型选择器滑块的最高档位。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "voice_enabled"],
      label: "启用语音界面",
      group: "语音与听写",
      kind: "boolean",
      description: "客户端默认开启；实际语音执行仍依赖可用服务。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "dictation_enabled"],
      label: "启用听写",
      group: "语音与听写",
      kind: "boolean",
      description: "客户端默认开启；麦克风仍需系统授权。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "developer_mode"],
      label: "开发者模式",
      group: "开发与安全",
      kind: "boolean",
      description: "显示客户端开发者功能。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "connector_enforce_csp_in_dev_mode"],
      label: "开发模式下执行连接器 CSP",
      group: "开发与安全",
      kind: "boolean",
      description: "保持连接器内容安全策略检查。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "enable_device_code_auth"],
      label: "允许设备码登录",
      group: "开发与安全",
      kind: "boolean",
      description: "客户端设备码登录偏好，不替代实际认证。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "enable_flora_network_access"],
      label: "允许浏览器功能访问网络",
      group: "开发与安全",
      kind: "boolean",
      description: "保存客户端对应网络访问偏好，保留其他权限检查。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "enable_remote_browser_data"],
      label: "允许远程浏览器数据",
      group: "开发与安全",
      kind: "boolean",
      description: "保存客户端的远程浏览器数据偏好。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "lockdown_mode_enabled"],
      label: "锁定模式",
      group: "开发与安全",
      kind: "boolean",
      description: "控制客户端锁定模式偏好。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "precise_location_allowed"],
      label: "允许精确位置",
      group: "隐私与个性化",
      kind: "boolean",
      description: "保存位置偏好；不会授予操作系统位置权限。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "training_allowed"],
      label: "允许数据改进",
      group: "隐私与个性化",
      kind: "boolean",
      description: "仅保存本虚拟账号的客户端偏好，不代表供应服务的训练政策已改变。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "bazaar_personalization_enabled"],
      label: "个性化推荐",
      group: "隐私与个性化",
      kind: "boolean",
      description: "客户端默认开启个性化推荐。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "free_ads_opt_out"],
      label: "退出免费版广告个性化",
      group: "隐私与个性化",
      kind: "boolean",
      description: "保存客户端的广告退出偏好。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "trusted_contacts_opted_out_at"],
      label: "不再提示信任联系人",
      group: "隐私与个性化",
      kind: "boolean",
      description: "该版本客户端将此字段读取为布尔值。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "chat_theme"],
      label: "聊天主题色",
      group: "外观",
      kind: "select",
      description: "使用客户端支持的主题色。",
      choices: [
        ["default", "默认"],
        ["blue", "蓝色"],
        ["green", "绿色"],
        ["yellow", "黄色"],
        ["pink", "粉色"],
        ["orange", "橙色"],
        ["purple", "紫色"],
        ["black", "黑色"],
      ],
      optional: true,
    },
    {
      path: ["settings", "wingman_thinking_effort"],
      label: "语音思考强度",
      group: "语音与听写",
      kind: "select",
      description: "客户端支持即时、中等和高三档。",
      choices: [
        ["instant", "即时"],
        ["medium", "中等"],
        ["high", "高"],
      ],
      optional: true,
    },
    {
      path: ["settings", "birthday"],
      label: "生日",
      group: "个人资料",
      kind: "date",
      description: "使用年-月-日格式，留空使用客户端默认。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "accessory_id"],
      label: "所选配饰",
      group: "外观",
      kind: "string",
      description: "由客户端选择并保存。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "contrast_mode"],
      label: "对比度模式",
      group: "外观",
      kind: "string",
      description: "由客户端选择并保存。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "voice_main_language"],
      label: "语音主要语言",
      group: "语音与听写",
      kind: "string",
      description: "由客户端选择并保存。",
      choices: [],
      optional: true,
    },
    {
      path: ["settings", "voice_mode"],
      label: "语音模式",
      group: "语音与听写",
      kind: "string",
      description: "由客户端选择并保存。",
      choices: [],
      optional: true,
    },
    {
      path: ["flags", "bazaar_consent_required"],
      label: "推荐功能需要同意",
      group: "界面可用状态",
      kind: "boolean",
      description: "要求客户端显示推荐功能同意流程。",
      choices: [],
      optional: true,
    },
    {
      path: ["flags", "bazaar_personalization_unavailable"],
      label: "推荐个性化不可用",
      group: "界面可用状态",
      kind: "boolean",
      description: "控制客户端个性化功能的可用状态。",
      choices: [],
      optional: true,
    },
    {
      path: ["flags", "file_library_enabled_for_registration_country"],
      label: "所在地区可使用文件库",
      group: "界面可用状态",
      kind: "boolean",
      description: "本地配置的界面可用状态，不代表官方地区资格。",
      choices: [],
      optional: true,
    },
  ],
  config_bundle: [],
  referral_tracking: [],
  payment_methods: [],
  family: [],
  notification_settings: [],
  notifications: [],
  pins: [],
  projects: [],
  models: [],
  auto_top_up: [],
  verified_access: [],
  automations: [],
  installed_plugins: [],
  voice: [],
  onboarding: [],
  browser_settings: [],
};
